### PR TITLE
Feat/v4

### PR DESCRIPTION
**Pull request by fabriziomoscon**

### CODE REVIEW

**Comment by fabriziomoscon** [comment]
@Pagebakers @gitstud my intention is to release breaking changes with this branch and on top of it add test #127 
any help in testing this would br greatly appreciated.

**Comment by jdegger** [comment]
@fabriziomoscon when you have a working fork (with or without breaking changes) which works for both iOS and Android, we are willing to immediately test it throughougly for you. Please ping us when we are needed!

(cc: @wesdewitte)

**Comment by fabriziomoscon** [comment]
@jdegger I have been testing this branch for a long time and it works on real device for real calls, but it doesn't use Twilio's latest library, because I didn't notice there were going to be deprecations. The code in #127 should be added on top of it to test more, then we will need to add the new iOS twilio SDK and integrate changes

**Comment by jdegger** [comment]
@fabriziomoscon Sounds good. Your work is aimed at SDK4, however SDK5 is already been released. Would this be an opportunity to immediately go for V5?

At the moment we do not have the development power to actually help with the PR, however let me know if it needs any testing or if you need help on _any_ other aspect.

**Comment by Pagebakers** [comment]
Great to see some action here :)

I'll have a look if I can merge this next week.

**Comment by fabriziomoscon** [comment]
@jdegger this branch is called v4 for RNtwilio breaking changes from v3, when I started the work there weren't SDK above V2 from twilio.
I need to look better into #127 to fully answer your question.

**Comment by fabriziomoscon** [comment]
Correction: Yesterday I mistaken referenced issue 127 when I meant PR 130 - changed my comments.

**Comment by gitstud** [comment]
Commits are clean! I will try to test this out on iOS this weekend

**Comment by aniravi24** [comment]
Is this removing the firebase service on Android that shows notification for your incoming calls->ongoing calls->missed calls? Or does that still work?

**Comment by fabriziomoscon** [comment]
@aniravi24 if that is the case it was not done on purpose.
`implementation 'com.google.firebase:firebase-messaging:17.+'` is still there.
I guess I will need to test more for this specific case on Android.

**Comment by aniravi24** [comment]
Got it. I saw it was removed from AndroidManifest.xml so that's why I thought it was being removed.

**Comment by gitstud** [comment]
Module TwilioVoice not found
Tried first with autolinking, and then react-native link <package> and then manual link
pod is installed, lib is linked, and node_module is linked

"react-native": "0.61.5"

**Comment by gitstud** [comment]
I didn't see my logs in deviceReady or deviceNotReady, I was able to make an outbound call and hangup

**Comment by aniravi24** [comment]
Working fine on Android for us! We'll give iOS a test soon too.

**Comment by aniravi24** [comment]
Looks good.

**Comment by fabriziomoscon** [comment]
these commits are now included into https://github.com/hoxfon/react-native-twilio-programmable-voice/pull/144

**Pull request closed without merging**
