### PR TITLE
fix missing params that pass to twilio

### PR DESCRIPTION
**Pull request by gongdao123**
Allow user to pass custom params to Twilio.

### CODE REVIEW

**Comment by theill** [comment]
This works great. I think you should merge it to master @fabriziomoscon when you get a chance.

**Comment by fabriziomoscon** [comment]
@gongdao123 this looks great. I have 3 questions:
- what is the use case?
- should this be added to iOS as well?
- could you move the function that iterates through the Map into a separate file?

**Comment by theill** [comment]
The use case is to be able to pass additional parameters to your connect call. These extra parameters will Twilio pass through to your own code which you can use e.g. when generating TwiML code or similar.

IOS already pass the params through

```_callParams = [[NSMutableDictionary alloc] initWithDictionary:params];```

so no changes needed there.

**Comment by gongdao123** [comment]
@fabriziomoscon Sorry for the late response. As for your questions, I think @theill already answered them.

**Comment by rhussmann** [comment]
+1 for this PR. I've used the fork above for my own application where I need to pass additional parameters to Twilio. This is a valid use case. Twilio supports passing additional parameters to the `/voice` callback (or whatever you've defined), by passing them in the `TwilioVoice.connect()` function, along with the `To` parameters.

This feature allows clients to pass additional context to their TWiML server callback endpoint. For instance, calling:

```
TwilioVoice.connect({
  To: "5555555555",
  ContextBitA: "SomeContext",
  ContextBitB: "SomeOtherContext",
});
```
will result in the TWiML callback endpoint being invoked with not only `To:` in the POST body, but also `ContextBitA` and `ContextBitB` in the POST body as well. This functionality is supported by Twilio, and this PR adds this functionality to Android implementation.

Please merge this PR.

**Comment by jdegger** [comment]
Can this _please_ be merged. On iOS this behavior works fine and we rely on it to check some device-keys server side. However this is not working on Android right now and we have an extra layer of security disabled.

**Comment by fabriziomoscon** [comment]
Understood that this is a good change, I need to find the time to integrate and publish.
Possibly check for breaking changes as well...

**Comment by jdegger** [comment]
As there were only a few keys passed it was easily checked if behavior breaks and so far we do not see anything breaking when copying this PR into our local files.

Let me know if we can assist and/or test

**Comment by jdegger** [comment]
Thanks for merging this @fabriziomoscon! Appreciated. When do you think this will land in the next release?

**Comment by fabriziomoscon** [comment]
npm `react-native-twilio-programmable-voice@3.21.0`

Thanks to @gongdao123 and to all involved in testing it!

**Pull request merged**
