### PR TITLE
WIP Original jrperson ios

### PR DESCRIPTION
**Pull request by fabriziomoscon**
@nkarman
@jrperson
I started review the ios code for integration. Please check it out and tell me what you think

### CODE REVIEW

**Comment by jrperson** [comment]
I ran through it and it looks good to me.

I wasn't sure if the pod files could be packaged inside, it was probably a wise choice to link the Twilio library outside of this one.  That is the way I did it in my own application, but tried it this way to possibly cut down on setup for others.

**Comment by fabriziomoscon** [comment]
@jrperson I could not make pods work with this library + https://github.com/tipsi/tipsi-stripe. So I tried to see what others do when it comes to external SDKs. This seems to work, but I am definitely not an expert on Pods nor on Xcode. Having a 70Mb file under git doesn't sound super smart. But who knows?

**Comment by nkarman** [comment]
Hey @jrperson Thanks for contributing so much to this repo. I was hoping you could provide some insight regarding the functionality of this node module with Twilio's SDK. Currently, We are running the most recent version of this node module with TwilioVoice sdk 2.0.0Beta11, as denoted in the docs. We are using Twilio VoiceClient to connect users for an App to App phone call. 

We have had several successful calls, but more often than not, the call connects then is immediately dropped, or the audio is not connected between users. We are shooting in the dark, and would really appreciate some insight. I saw that you mentioned somewhere that you had this running perfectly in your app. Wondering what version you are using and if there is any advice you could offer us to get Twilio client calling working seamlessly in our application. Thanks so much in advance, we really appreciate that you brought iOS functionality to this module.

**Comment by fabriziomoscon** [comment]
@nkarman I saw your messages just now.
I am using the ios part of this library without the issues you are encountering.
I want to update it to the latest Twilio sdk as well.
https://www.twilio.com/docs/api/voice-sdk/ios/changelog
If you are in the process of doing it, a PR would be more then welcome.

**Pull request merged**
