### PR TITLE
Twilio Voice Android SDK 5

### PR DESCRIPTION
**Pull request by aniravi24**
This builds on top of the migration to Android SDK v4.

Definitely load the diff for the main voice module - that's where most of the changes are. The readme hasn't been updated to indicate the different states that are hardcoded in the module - still haven't totally decided on that but it works! Many of the changes are just Android studio formatting.

I'd also like to update the package version to 5.0.0 - maybe we should keep it the same version as the twilio libraries we use so it's less confusing.

### CODE REVIEW

**Comment by aniravi24** [comment]
Definitely load the diff for the main voice module - that's where most of the changes are. The readme hasn't been updated to indicate the different states that are hardcoded - still not totally sure on that but it works!

**Comment by aniravi24** [comment]
@fabriziomoscon sorry about that! Accidentally let Android studio format everything. Instead of making a whole new PR, mind if I leave comments in the places where I actually made changes? Would that work?

**Comment by fabriziomoscon** [comment]
Formatting should always be added as a separate commit. The reason is not limited to code review, since the commit history will be used by users to understand when and what change has been added when they are debugging their app.
All commits should be grouped when the refer the the same logical change, so formatting can be quickly ignored

**Comment by aniravi24** [comment]
Got it - will do another PR when I get a chance with only the changes made.

**Comment by fabriziomoscon** [comment]
@aniravi24 thanks for your contributions.
Your fixes are now incorporated into https://github.com/hoxfon/react-native-twilio-programmable-voice/pull/144
I noticed that there might be functional changed or improvements on the set audio calls, but I would advise to add such changes on top of the final merge which I plan to land as v4.0.0 of this library.

**Comment by aniravi24** [comment]
@fabriziomoscon sorry for the delay! Thank you for doing that. That code comes straight from the Twilio quickstart for Android.

**Pull request closed without merging**
