### PR TITLE
add cocoapods support to install iOS native package 

### PR DESCRIPTION
**Pull request by noamSoluto**
we have a old react native project which was not created by using the react-native init command. therefore we need the .podspec file for adding the native code to our project.

### CODE REVIEW

**Comment by fabriziomoscon** [comment]
Hi @noamSoluto thanks for this addition.
I have two questions:
- Why did you comment out `checkPermissionForMicrophone()` in Android? If there is an issue with checking microphone permissions on Android, please submit a different PR so it can be processed separately.
- I was not aware of the need to add a podspec file, could you please point me to the relative documentation/examples so I can learn more about it.

Thank you

**Comment by noamSoluto** [comment]
hi @fabriziomoscon ,
1. I comment out the checkPermissionForMicrophone() in Android, because I want to request the microphone permission only when the user starts calling someone. I reverted the comment as your request.
2. you can find [here](https://guides.cocoapods.org/making/specs-and-specs-repo.html) some information about the podspec file and you can see some usage in libraries like:
[react-native-image-picker](https://github.com/react-community/react-native-image-picker)
[react-native-permissions](https://github.com/yonahforst/react-native-permissions)
[lottie-react-native](https://github.com/airbnb/lottie-react-native)

thanks,
Noam

**Comment by slootzky** [comment]
Hey @fabriziomoscon ,
any progress with this PR?

**Comment by fabriziomoscon** [comment]
Hi @slootzky, thanks for  bringing this to my attention.
Twilio has released the stable version 2 and I have updated this library.

```
source 'https://github.com/cocoapods/specs'

# min version for TwilioVoice to work
platform :ios, '8.1'

target <YOUR_TARGET> do
    ...
    pod 'TwilioVoice', '~> 2.0.0'
    ...
end
```
@noamSoluto could you please rebase this PR in top of master and squash commits into 1, so I can merge

**Comment by fabriziomoscon** [comment]
@noamSoluto thanks for synching with master.
I can see something hasn't worked out properly since there are 32 commits now. Any chance you used
`git merge master`
I can't really merge this work as it is.
Since the changes affect only 2 files I would suggest to start afresh from a new branch from master and add the changes and submit another branch and PR.

Sorry for asking you to do extra work.

**Comment by noamSoluto** [comment]
ok @fabriziomoscon , I will create new PR

**Pull request closed without merging**
