### PR TITLE
Make sure CallKit session is ended on fail

### PR DESCRIPTION
**Pull request by Pagebakers**
This fixes an issue where the CallKit session isn't ended when making an outbound call fails. Keeping the green topbar active when exiting the app.

### CODE REVIEW

**Comment by fabriziomoscon** [comment]
Thanks a lot!
I am experiencing this issue as well. I will test and merge as soon as possible

**Comment by SimonRobinson** [comment]
@Pagebakers @fabriziomoscon probably need to remove the same if statement from [callDidDisconnect](https://github.com/hoxfon/react-native-twilio-programmable-voice/pull/30/files#diff-e67091c1701490f5b837506d8029fe69L336) fn as well. For me if the caller hangs up first the callKit session is also not ended as when disconnect fires call.state is not connected.

```ObjectiveC
(void)callDidDisconnect:(TVOCall *)call
...
 if (self.call.state == TVOCallStateConnected) {
    [self performEndCallActionWithUUID:call.uuid];
 }
```
Should be just?
```ObjectiveC
  [self performEndCallActionWithUUID:call.uuid];
```

**Comment by fabriziomoscon** [comment]
I see.
I made these two changes in this commit:
https://github.com/hoxfon/react-native-twilio-programmable-voice/commit/4349162a318262c5dc43901748b27863c7a7c166
because the calls were not disconnected correctly.
So rather than remove the conditions all together I think we need to find the best way to disconnect all possible status of calls without leaving a zombie call in the background and without having errors in the log.
I will definitely test further the two scenarios you mentioned, but also it would be great if you can see and test what happens when you remove the commit I referred to

**Comment by SimonRobinson** [comment]
@fabriziomoscon ok got it, will have a test and let you know.

**Comment by oshimayoan** [comment]
Any progress on this?

**Comment by fabriziomoscon** [comment]
I haven't had time to test it yet.

**Comment by fabriziomoscon** [comment]
@SimonRobinson in the scenario you are describing is the iOS app making or receiving the call?

**Comment by fabriziomoscon** [comment]
@Pagebakers only today I could test your change I confirm that it is necessary. Well done and well spotted! My personal apologies for the delay to merge this change

**Comment by fabriziomoscon** [comment]
published on npm `2.11.1`

**Comment by fabriziomoscon** [comment]
@SimonRobinson you are right!
I added https://github.com/hoxfon/react-native-twilio-programmable-voice/commit/4349162a318262c5dc43901748b27863c7a7c166 to placate errors in the log, but as you pointed out the condition prevent a correct call disconnection in case the callee hangs the call up.

I have opened a separate issue to track this error in the log.
I will remove now the condition mentioned and published a new npm version.

Many thanks for your patience!

**Comment by fabriziomoscon** [comment]
the fix mentioned above has been published on npm `2.11.2`

**Comment by Pagebakers** [comment]
Great, thanks for merging this in!

**Comment by SimonRobinson** [comment]
@fabriziomoscon thanks for fixing and merging. FYI was testing with receiving calls.

**Pull request merged**
