### PR TITLE
iOS Implimentation

### PR DESCRIPTION
**Pull request by jrperson**
I have Twilio Programmable Voice working perfectly within my own React Native app for iOS. As I intend to now move to Android, I thought I would try to pull my code over to be included in this library to help someone else out.

I built the functionality outside of this library, so I pulled out the relevant bits from my own project and put it in my fork. I haven't tested it from within the library yet, but the structure is all there that I used. My biggest reservation is the linking of the Twilio library that is pulled in through the Podfile as I haven't tested it from within the library yet.

I utilized CallKit as it is super easy and much more integrated on iOS than manually handling calls. Because of this, my implementation is missing manual calls for "accept", "reject", and "ignore."

### CODE REVIEW

**Comment by fabriziomoscon** [comment]
@jrperson thank you so much for contributing!
I am really looking forward to test your implementation, most probably I will check it out next week. Meanwhile I am also updating the Android part to align with the official Twilio SDK, see #14 and #17.
Thanks again for contributing.
cc @bchen-twilio @idelgado

**Comment by jrperson** [comment]
After starting work on the Android part of this library, I must state that my iOS version uses Twilio's Beta 5 version.

I am working through modifying Android side to work with Beta 5 currently as I already use FCM in my application and don't want to switch to GCM.

**Comment by fabriziomoscon** [comment]
Thank you for the work on iOS!
The migration to beta5 was in the plan, but if you beat me I am happy.
Just so you know, I am also using FCM in my App and the current master implementation works. Even tough it uses beta4.
I have pushed a new master version on npm this morning fixing a small bug.

Also I noticed there is another iOS fork with working code, but not PR yet. 
https://github.com/nkarman/react-native-twilio-programmable-voice

**Comment by jrperson** [comment]
@fabriziomoscon I'll open an issue on the FCM/GCM problem I am having.

**Comment by fabriziomoscon** [comment]
@jrperson I started the migration to FCM with beta5, it is quite complex, so I would advise to wait until I produce it and then try again with your app. There big migrations from GCM to FCM.
Afterwards you could rebase this PR in top of master so it can be merged.
How does it sound?

**Comment by fabriziomoscon** [comment]
@jrperson If you want to test it I opened a PR for beta5 #21

**Comment by fabriziomoscon** [comment]
@jrperson I opened a new PR
https://github.com/hoxfon/react-native-twilio-programmable-voice/pull/22

- used beta9
- renamed TwilioVoice to RNTwilioVoice to avoid name clash

I look forward to hearing your comments

**Comment by jrperson** [comment]
@fabriziomoscon I will try it out when I go back through the code.  I saw that you couldn't get it to work with react-native-fcm and I am using that library as well.  It will probably come down to bringing that code into this library to eliminate the conflicts.

I will take a look at this when I circle back around on it.

**Comment by fabriziomoscon** [comment]
@jrperson the problem with `react-native-fcm` and this lib is that both needs to add a service in the manifest to handle the push. I was not able to make them work together in my app. But at this stage my app doesn't have the need to handle push notifications apart from the calls.
I would be great to find out a way to let them both work.

**Pull request closed without merging**
