### PR TITLE
Twilio Voice Android SDK 4

### PR DESCRIPTION
**Pull request by Pagebakers**
Upgraded to the new SDK

I'm not an Android developer, but need our apps to be updated, so here goes nothing :)

Basic functions seem to work.

Haven't implemented the new onRinging/onReconnecting/onReconnecting callbacks
callInvite.getState() is not available anymore, removed this where used, but not sure if this breaks anything.

Need testers! :)

### CODE REVIEW

**Comment by aniravi24** [comment]
It looks like getState() got moved under Call, rather than CallInvite.

**Comment by gitstud** [comment]
Would be happy to review this when I get some time, hopefully next weekend

**Comment by Pagebakers** [comment]
Greatly appreciated!

**Comment by gitstud** [comment]
Code looks good! I think the comments should come out where you took out the getState calls.  I'll get a chance to run it tomorrow or Sunday and let you know how that went

**Comment by aniravi24** [comment]
I think the state got moved to another class, and it would be ideal if we could figure out a way to keep the state information because I have an app that actually relies on it to not show calls after they are already over.

**Comment by Pagebakers** [comment]
I've been running this partly successful on our app for 2 months now.

We do get this error every now and then though:

```
java.lang.NullPointerException · Attempt to invoke interface method 'com.facebook.react.ReactNativeHost com.facebook.react.ReactApplication.getReactNativeHost()' on a null object reference
VoiceFirebaseMessagingService.java:78com.hoxfon.react.RNTwilioVoice.fcm.VoiceFirebaseMessagingService$1$1.run	
Handler.java:873android.os.Handler.handleCallback	
Handler.java:99android.os.Handler.dispatchMessage	
Looper.java:201android.os.Looper.loop	
ActivityThread.java:6806android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
RuntimeInit.java:547com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run	
ZygoteInit.java:873com.android.internal.os.ZygoteInit.main
```

Anyone any idea how to fix this?

**Comment by jdegger** [comment]
@Pagebakers We tested this as well, but as we understood it (according to your commits), your changes were Android-only. Is this correct?

**Comment by Pagebakers** [comment]
Thanks for testing, this update is Android only indeed.

There's another PR for the IOS update.

**Comment by fabriziomoscon** [comment]
Just to coordinate... 
I am awaiting from @Pagebakers @jdegger and @gitstud to complete tests this weekend so on Monday we can confirm that branch `feat/v4` could be a stepping stone for this PR and the iOS one. Did I miss something?

**Comment by jdegger** [comment]
@Pagebakers @fabriziomoscon Can the PRs be combines so it testable on both platforms in one go?

**Comment by fabriziomoscon** [comment]
I think the merging order should be: feat/v4, android SDK v4, and IoS

**Comment by Pagebakers** [comment]
@fabriziomoscon That was pretty painless

No issues running this on first sight.

**Comment by fabriziomoscon** [comment]
Thanks @Pagebakers you will need to rebase master to fix the above conflicts. I am testing now

**Comment by fabriziomoscon** [comment]
@Pagebakers I noticed that you merged half of my PR. Please check the full list here: https://github.com/hoxfon/react-native-twilio-programmable-voice/pull/108/commits
I am going to open a new branch with all rebasing

**Comment by Pagebakers** [comment]
Oh shit something went wrong then, I'll look into it tomorrow.

**Comment by fabriziomoscon** [comment]
@Pagebakers I pushed a branch here containing the latest master `feat/v4` and your work in this order.
Could you run a test please?
https://github.com/hoxfon/react-native-twilio-programmable-voice/tree/feature/android-sdk-4 should be ready to be tested

**Comment by Pagebakers** [comment]
Getting a compilation error, but that may be due my bad internet connection. I'll need to try it again on wifi later.

**Comment by fabriziomoscon** [comment]
My compilation error was on voice.register() and using twilio 4.5.0 fixed it, what is yours?

**Comment by gitstud** [comment]
@fabriziomoscon I'm seeing this as well

**Comment by Pagebakers** [comment]
Getting a lot of cannot find symbol errors on the package in your branch unfortunately. Missing androidx classes.

error: cannot find symbol class NonNull

What React version have you been testing on?

**Comment by fabriziomoscon** [comment]
RN 0.60

**Comment by Pagebakers** [comment]
OK I figured, tried to upgrade now getting the same voice.register error, twilio 4.5.0 doesn't seem to fix this though :(

**Comment by Pagebakers** [comment]
Running in too much compilation errors now because of the upgrade, don't have the time for this unfortunately.

0.59.9 was running fine

https://github.com/forwarder/react-native-twilio-programmable-voice/blob/feature/android-sdk-4/android/src/main/java/com/hoxfon/react/RNTwilioVoice/TwilioVoiceModule.java#L576

Should become
```
                            Voice.register(accessToken, Voice.RegistrationChannel.FCM, fcmToken, registrationListener);

```

**Comment by fabriziomoscon** [comment]
@Pagebakers I know it is taking me more than 10 working days for me to upgrade to RN0.60, however it is a needed change for my app because of other libraries that have new features only for RN0.60.
Personally I am not interested in compiling for RN below 0.60, so possibly we could partition the PRs work, I will keep working on integrating your changes for RN0.60, feel free to push a PR for 0.59 if you think that is the best for your app.

**Comment by Pagebakers** [comment]
Surething, just go ahead releasing this for 0.60. I'll work it out once I find some more spare time. thanks!

**Comment by aniravi24** [comment]
You can probably use jetifier to fix the compilation errors if it's looking for androidx stuff. RN 0.60 as well as Android has made some changes to the underlying support libraries. If you're not on RN 0.60 or above, try installing https://www.npmjs.com/package/jetifier and running `npx jetify` in your repo. We use RN 0.61.5 with a production app with the latest npm version of this package and I'm looking forward to testing some of the new work in these branches in the next few days!

**Comment by Pagebakers** [comment]
Took me a couple more hours, but the solution is easy 
Using the reverse option makes it work for < 0.60
```
npx jetify -r
```

Thanks @aniravi24 for getting me to the right direction :)

Still getting an error though
```
java.lang.RuntimeExceptionTwilioVoiceModule.java:561
Could not invoke RNTwilioVoice.initWithAccessToken
```

**Comment by aniravi24** [comment]
As soon as I take an incoming call, it seems to fail to connect (doesn't run connectionDidConnect) and automatically fires the disconnect listener. Investigating to figure out why that's happening.

**Comment by aniravi24** [comment]
I also have #142 in on top of the work in feature/android-sdk-4.

**Comment by fabriziomoscon** [comment]
These changes have been included in #144

**Pull request closed without merging**
